# Generated by Django 3.2.5 on 2021-07-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210703_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[(1, 'Средняя'), (2, 'Гимназия'), (3, 'Лицей'), (4, 'Частная'), (5, 'Интернат'), (6, 'Спорт Школа')], default='Школа', max_length=255),
        ),
    ]
